# suppliers_data.py
# Contains known suppliers with their pre-assessed risk profiles and metadata

suppliers_data = {
    "Microsoft": {
        "metadata": {"sector": "Technology", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Local / EU",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Technical support",
            "3️⃣ Sector & Activity Criteria_System access": "Limited access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Limited",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Personal data",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "None",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "None",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Google": {
        "metadata": {"sector": "Technology", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Local / EU",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Technical support",
            "3️⃣ Sector & Activity Criteria_System access": "Limited access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Limited",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Amazon Web Services (AWS)": {
        "metadata": {"sector": "Cloud Services", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Core business dependency",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Regulated region",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Managed",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Apple": {
        "metadata": {"sector": "Technology", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Local / EU",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Technical support",
            "3️⃣ Sector & Activity Criteria_System access": "Limited access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Limited",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Personal data",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Oracle": {
        "metadata": {"sector": "Enterprise Software", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Regulated region",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Managed",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "SAP": {
        "metadata": {"sector": "Enterprise Software", "geography": "Germany", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Core business dependency",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Local / EU",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Cisco": {
        "metadata": {"sector": "Hardware", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Regulated region",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Technical support",
            "3️⃣ Sector & Activity Criteria_System access": "Limited access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Limited",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Internal data",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "None",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "None",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Accenture": {
        "metadata": {"sector": "Consulting & Professional Services", "geography": "Ireland", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Local / EU",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Business support",
            "3️⃣ Sector & Activity Criteria_System access": "Limited access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Personal data",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "None",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "None",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "JPMorgan Chase": {
        "metadata": {"sector": "Financial Services", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Core business dependency",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Local / EU",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "Finance / Health",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Managed",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Verizon": {
        "metadata": {"sector": "Telecom", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Regulated region",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "Telecom / Gov",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Managed",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Pfizer": {
        "metadata": {"sector": "Healthcare", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Core business dependency",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Local / EU",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "Finance / Health",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Salesforce": {
        "metadata": {"sector": "Enterprise Software", "geography": "USA", "size": "Large"},
        "profile": {
            "1 Supplier General Characteristics_Supplier criticality": "Important service",
            "1 Supplier General Characteristics_Supplier size": "Multinational",
            "1 Supplier General Characteristics_Years of activity": ">10 years",
            "1 Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2 Geographical Risk Criteria_Country risk": "Stable country",
            "2 Geographical Risk Criteria_Data hosting location": "Regulated region",
            "2 Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2 Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3 Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3 Sector & Activity Criteria_Service type": "Core operations",
            "3 Sector & Activity Criteria_System access": "High access",
            "3 Sector & Activity Criteria_Process outsourcing": "Partial",
            "4 Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4 Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4 Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4 Information Security & Cyber Risk_Access management": "Strong IAM",
            "5 Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5 Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5 Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5 Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6 Financial & Legal Risk_Financial stability": "Strong growth",
            "6 Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6 Financial & Legal Risk_Insurance": "Full coverage",
            "6 Financial & Legal Risk_Litigation history": "Rare",
            "7 ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7 ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7 ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7 ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Apple": {
        "metadata": {"sector": "Technology", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Local / EU",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Technical support",
            "3️⃣ Sector & Activity Criteria_System access": "Limited access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Limited",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Personal data",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Oracle": {
        "metadata": {"sector": "Enterprise Software", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Regulated region",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "SAP": {
        "metadata": {"sector": "Enterprise Software", "geography": "Germany", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Core business dependency",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Local / EU",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Cisco": {
        "metadata": {"sector": "Hardware", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Regulated region",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Technical support",
            "3️⃣ Sector & Activity Criteria_System access": "Limited access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Limited",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Internal data",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "None",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "None",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Accenture": {
        "metadata": {"sector": "Consulting & Professional Services", "geography": "Ireland", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Local / EU",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Business support",
            "3️⃣ Sector & Activity Criteria_System access": "Limited access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Personal data",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "None",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "None",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "JPMorgan Chase": {
        "metadata": {"sector": "Financial Services", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Core business dependency",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Local / EU",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "Finance / Health",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Managed",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Verizon": {
        "metadata": {"sector": "Telecom", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Regulated region",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "Telecom / Gov",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Managed",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Pfizer": {
        "metadata": {"sector": "Healthcare", "geography": "USA", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Core business dependency",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Local / EU",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "Finance / Health",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Alibaba": {
        "metadata": {"sector": "Retail & E-commerce", "geography": "China", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Politically sensitive",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "High-risk country",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "Partial compliance",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Limited control",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "Non-sensitive",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Personal data",
            "4️⃣ Information Security & Cyber Risk_Security certification": "Partial",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Standard controls",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Documented",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Moderate",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Standard SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Mostly compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Adequate",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Internal policy",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Managed",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Basic"
        }
    },
    "Tencent": {
        "metadata": {"sector": "Technology", "geography": "China", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Politically sensitive",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "High-risk country",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "Partial compliance",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Limited control",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Technical support",
            "3️⃣ Sector & Activity Criteria_System access": "Limited access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Limited",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Personal data",
            "4️⃣ Information Security & Cyber Risk_Security certification": "Partial",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Standard controls",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Documented",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Moderate",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Standard SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Mostly compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Adequate",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Internal policy",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Managed",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Basic"
        }
    },
    "Siemens": {
        "metadata": {"sector": "Industrial", "geography": "Germany", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Core business dependency",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Local / EU",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Stable",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Reliance Industries": {
        "metadata": {"sector": "Energy", "geography": "India", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Core business dependency",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Emerging economy",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Regulated region",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "Local compliance",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Contractual control",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Highly confidential",
            "4️⃣ Information Security & Cyber Risk_Security certification": "Partial",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Standard controls",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Documented",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Moderate",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Standard SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Mostly compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Adequate",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Internal policy",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Managed",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Basic"
        }
    },
    "Samsung": {
        "metadata": {"sector": "Hardware", "geography": "South Korea", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Regulated region",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "Local compliance",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Contractual control",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "IT services",
            "3️⃣ Sector & Activity Criteria_Service type": "Technical support",
            "3️⃣ Sector & Activity Criteria_System access": "Limited access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Limited",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Internal data",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "Minor incidents",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "Rare",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Managed",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Toyota": {
        "metadata": {"sector": "Automotive", "geography": "Japan", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Regulated region",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "Local compliance",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Contractual control",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "Non-sensitive",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "High access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Partial",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Internal data",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "None",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Strong growth",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "None",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    },
    "Unilever": {
        "metadata": {"sector": "Consumer Goods", "geography": "UK", "size": "Large"},
        "profile": {
            "1️⃣ Supplier General Characteristics_Supplier criticality": "Important service",
            "1️⃣ Supplier General Characteristics_Supplier size": "Multinational",
            "1️⃣ Supplier General Characteristics_Years of activity": ">10 years",
            "1️⃣ Supplier General Characteristics_Dependency level": "Multiple suppliers",
            "2️⃣ Geographical Risk Criteria_Country risk": "Stable country",
            "2️⃣ Geographical Risk Criteria_Data hosting location": "Local / EU",
            "2️⃣ Geographical Risk Criteria_Regulatory alignment": "GDPR / strong laws",
            "2️⃣ Geographical Risk Criteria_Cross-border data flow": "Fully regulated",
            "3️⃣ Sector & Activity Criteria_Sector sensitivity": "Non-sensitive",
            "3️⃣ Sector & Activity Criteria_Service type": "Core operations",
            "3️⃣ Sector & Activity Criteria_System access": "Limited access",
            "3️⃣ Sector & Activity Criteria_Process outsourcing": "Limited",
            "4️⃣ Information Security & Cyber Risk_Data sensitivity": "Internal data",
            "4️⃣ Information Security & Cyber Risk_Security certification": "ISO 27001 / SOC2",
            "4️⃣ Information Security & Cyber Risk_Incident history": "None",
            "4️⃣ Information Security & Cyber Risk_Access management": "Strong IAM",
            "5️⃣ Business Continuity & Operational Risk_BCP / DRP": "Tested & audited",
            "5️⃣ Business Continuity & Operational Risk_RTO / RPO": "Optimized",
            "5️⃣ Business Continuity & Operational Risk_SLA availability": "Strong SLA",
            "5️⃣ Business Continuity & Operational Risk_Subcontracting": "Controlled",
            "6️⃣ Financial & Legal Risk_Financial stability": "Stable",
            "6️⃣ Financial & Legal Risk_Legal compliance": "Fully compliant",
            "6️⃣ Financial & Legal Risk_Insurance": "Full coverage",
            "6️⃣ Financial & Legal Risk_Litigation history": "None",
            "7️⃣ ESG & Ethical Criteria_Ethics policy": "Enforced",
            "7️⃣ ESG & Ethical Criteria_Anti-corruption": "Audited program",
            "7️⃣ ESG & Ethical Criteria_Environmental impact": "Sustainable",
            "7️⃣ ESG & Ethical Criteria_Social responsibility": "Certified / audited"
        }
    }
}